### ISSUE TITLE
Who is admin on this repo?

### ISSUE THREAD

**Issue by danwiththeplan** [PlantandFoodResearch/PFRAutomatedWorkflows#27]
At a recent meeting we decided to use this repo to put nextflow automated workflows, since there are some already here. Who is managing this repo now that @hdzierz  is gone? @kiwiroy @cflsjt can I get admin rights?

**Comment by cflsjt** [comment]
@danwiththeplan I THINK it's done...

**Comment by danwiththeplan** [comment]
@cflsjt done thanks!
